# Generated by Django 6.0.3 on 2026-03-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(blank=True, default='', max_length=998)),
                ('from_email', models.CharField(blank=True, default='', max_length=254)),
                ('to_emails', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('error', models.TextField(blank=True, default='')),
            ],
        ),
    ]
