# Generated by Django 6.0.3 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="postgres_dsn",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
    ]

