# Generated by Django 6.0.3 on 2026-03-27 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_postgres_dsn'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('value', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='users.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'key'], name='users_userv_profile_38aa37_idx')],
                'unique_together': {('profile', 'key')},
            },
        ),
    ]
