# Generated by Django 6.0.3 on 2026-03-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_uservariable'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservariable',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
    ]
